/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ActivitiesActivityNameIndexImport } from './routes/activities/$activityName/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ActivitiesActivityNameIndexRoute =
  ActivitiesActivityNameIndexImport.update({
    id: '/activities/$activityName/',
    path: '/activities/$activityName/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/activities/$activityName/': {
      id: '/activities/$activityName/'
      path: '/activities/$activityName'
      fullPath: '/activities/$activityName'
      preLoaderRoute: typeof ActivitiesActivityNameIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities/$activityName': typeof ActivitiesActivityNameIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities/$activityName': typeof ActivitiesActivityNameIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/activities/$activityName/': typeof ActivitiesActivityNameIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activities/$activityName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activities/$activityName'
  id: '__root__' | '/' | '/activities/$activityName/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesActivityNameIndexRoute: typeof ActivitiesActivityNameIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesActivityNameIndexRoute: ActivitiesActivityNameIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/activities/$activityName/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/activities/$activityName/": {
      "filePath": "activities/$activityName/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
